spring:
  application:
    name: global-config

logging:
  level:
    root: INFO
    org.springframework.cloud: INFO
    org.springframework.cloud.bus: DEBUG
    org.springframework.amqp: INFO

management:
  endpoints:
    web:
      exposure:
        include: health, info, env
