spring:
  application:
    name: scb-campaign-service
  cloud:
    bus:
      enabled: true

campaign:
  enabled: true
  type: SEASONAL-TEST
  discount-rate: 55
  response:
    message-prefix: "[CAMPAIGN-2]"
    include-discount: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,env
