spring:
  application:
    name: scb-campaign-service
  cloud:
    bus:
      enabled: true

campaign:
  enabled: true
  type: NEW-YEAR
  discount-rate: 42
  response:
    message-prefix: "[CAMPAIGN]"
    include-discount: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,refresh,busrefresh
